### ISSUE TITLE
Fix `rand(FixedRNG(), Bool)`

### ISSUE THREAD

**Issue by cscherrer** [JuliaMath/MeasureBase.jl#127]
Currently we have
```julia
(MeasureBase) pkg> st MeasureBase
Project MeasureBase v0.14.7
No Matches in `~/git/MeasureBase.jl/Project.toml`

julia> rand(FixedRNG(), Bool)
0.5
```

This is bad, since we should always have `rand(rng, T) isa T`. In particular, it gets in the way of https://github.com/JuliaMath/MeasureTheory.jl/pull/260

**Comment by oschulz** [comment]
Yes, I think `false` would be best? Or rather `true`?

**Comment by cscherrer** [comment]
Right, in https://github.com/JuliaMath/MeasureTheory.jl/pull/260 I'm temporarily adding "licensed type piracy", `MeasureBase.rand(::FixedRNG, ::Type{Bool}) = true`. I'll remove that once MB adds it

**Comment by cscherrer** [comment]
Closing this, ConstantRNGs.jl v0.1.1 addresses the issue
