### ISSUE TITLE
Adding a standard uniform, normal and exponential measure

### ISSUE THREAD

**Issue by oschulz** [JuliaMath/MeasureBase.jl#53]
It would be very useful to have the standard uniform, normal and exponential measure in MeasureBase. They are important as intermediates for variate transformations and can act as bridges for to Distributions as well, e.g. for transformations. Also, they correspond to Julia's native `rand()`, `randn()` and `randexp()`.

**Comment by cscherrer** [comment]
Done! Thanks @oschulz
