### ISSUE TITLE
Adding pushforward measures

### ISSUE THREAD

**Issue by oschulz** [JuliaMath/MeasureBase.jl#54]
A possible implementation would be a type `PushforwardMeasure(f, μ)` with a shorthand syntax `ν = f.(μ)` - this implies a monadic view of measures:

```julia
struct PushforwardMeasure{F,M} <: AbstractMeasure
    f::F
    orig::M
end

Random.rand(m::PushforwardMeasure) = m.f(rand(m.orig))

map(f, μ::AbstractMeasure) = PushforwardMeasure(f, μ)
Base.Broadcast.broadcasted(f, μ::AbstractMeasure) = map(f, μ)
```

**Comment by oschulz** [comment]
`PushforwardMeasure` would be a generalization of `MeasureTheory.Affine`.

`f` would be expected to support `ChangesOfVariables.with_logabsdet_jacobian`, and should support `InverseFunctions.inverse` as well if possible.

**Comment by cscherrer** [comment]
Ok, we already have
https://github.com/cscherrer/MeasureTheory.jl/blob/master/src/combinators/transforms.jl

But maybe it can be generalized beyond TransformVariables

**Comment by cscherrer** [comment]
Pushforwards need some updates (see https://github.com/JuliaMath/MeasureBase.jl/issues/125), but since there is an implementation I'll close this issue
